/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * Parsing a request part against its schema, and turning a failure into the one
 * documented `validation_failed` envelope.
 *
 * docs/17 §1: *"Data crossing a boundary — HTTP, queue, database row, environment — is
 * parsed into a domain type once, at the edge."* This module is that parse for HTTP, and
 * it lives in `packages/contracts` rather than in `apps/api` for two reasons that are
 * really one reason: the schemas are here, and so is `ApiError`. A mapping from a zod
 * failure to the wire shape of a 422 is a statement about the API's contract, and the
 * place that owns the contract should own it — otherwise the document says
 * `ValidationFailed` and the server decides, per route, what that actually looks like.
 *
 * ## Why this exists at all, when Fastify has a validator
 *
 * Fastify validates with ajv, and `@fastify/ajv-compiler` configures it with
 * `removeAdditional: true`. That turns `additionalProperties: false` into *"quietly strip
 * the field"* rather than *"refuse the request"*. For a login body that is harmless. For
 * a settings change it is a lie told to an administrator: the response says 200, the
 * audit row says nothing changed, and the field they sent is gone. A schema parsed here
 * with `strictObject` refuses instead, and the refusal names the key.
 *
 * Routes whose body genuinely wants ajv's coercion and defaulting — a query string, say —
 * keep using Fastify's `schema`. The two are not in competition: this is for the bodies
 * where "what exactly did you send me" is the question.
 *
 * ## What crosses to the client, and what does not
 *
 * Exactly two things per failure: the member of the request that failed (`body/branding`,
 * `body/branding/primary_colour`) and the rule it broke (`invalid_format`, `too_big`,
 * `unrecognized_keys`). Both are ours — they name a schema this service published — and
 * together they are enough for a client developer to fix the call.
 *
 * The validator's *message* is deliberately left out, and so is the offending value.
 * A message quotes the rule ("must match pattern ^https:\/\/…"), which hands an attacker
 * the shape of a check for free, and a value echoed back is user-controlled text on a
 * path that must never become a reflection (docs/14, error-message leakage).
 */

import './openapi-extension.js';

import type { z } from 'zod';

import { ApiError } from './errors.js';

/**
 * How many field failures are described before the list is cut.
 *
 * A bound rather than a formatting preference: the list is built from the caller's own
 * body, so an unbounded one is an unbounded response generated by whoever sent the
 * request. `apps/api`'s handler for ajv's failures uses the same number, because two
 * limits on one thing is one limit that is wrong.
 */
export const MAX_VALIDATION_FIELDS = 20;

/**
 * Which part of the request a schema is parsing.
 *
 * It becomes the first segment of every field path, so a client is told *where* the
 * problem is and not only what it is. The spellings match Fastify's own
 * `validationContext`, which is what `apps/api`'s error handler puts on the ajv-produced
 * failures — a client that learned to read one is reading the other.
 */
export type RequestPart = 'body' | 'querystring' | 'params' | 'headers';

/** One field failure, as it appears in `details.fields`. */
export interface ValidationField {
  /** `body/branding/primary_colour`. Slash-separated, rooted at the request part. */
  readonly field: string;
  /** The rule that was broken, as zod names it: `invalid_format`, `too_big`, `custom`. */
  readonly rule: string;
}

/** One issue, taken from zod's own error type rather than from its internals. */
type Issue = z.ZodError['issues'][number];

/**
 * Renders a path segment as text.
 *
 * `path` is `PropertyKey[]`, and `Array.prototype.join` throws on a symbol rather than
 * stringifying it — so a schema keyed by a symbol would turn a 422 into a 500. Nothing
 * in this package uses one today, which is exactly why it would be discovered late.
 */
function segment(key: PropertyKey): string {
  return typeof key === 'symbol' ? (key.description ?? 'symbol') : String(key);
}

/**
 * The fields a set of issues describes.
 *
 * An unrecognised key gets one entry per key, naming the key itself. zod reports it
 * against the *object* that carried it — the key is in `issue.keys`, not in `issue.path`
 * — so joining the path would produce `body/proctoring_defaults` for a request whose
 * actual problem was one field inside it, and the client would be told to look in the
 * wrong place.
 */
export function validationFieldsFor(
  issues: readonly Issue[],
  part: RequestPart,
): ValidationField[] {
  const fields: ValidationField[] = [];

  for (const issue of issues) {
    const path = [part, ...issue.path.map(segment)];

    if (issue.code === 'unrecognized_keys') {
      for (const key of issue.keys) {
        fields.push({ field: [...path, key].join('/'), rule: issue.code });
      }
      continue;
    }

    fields.push({ field: path.join('/'), rule: issue.code });
  }

  return fields;
}

/**
 * Parses `value` against `schema`, or throws the documented `validation_failed`.
 *
 * Returns the parsed value, which is the point: after this call the data has a domain
 * type it earned, and nothing downstream needs to half-trust it (docs/17 §1). The
 * original `ZodError` rides along as `cause`, so the log line under the request's trace
 * id has the full detail the response withholds.
 */
export function parseRequestPart<T>(schema: z.ZodType<T>, value: unknown, part: RequestPart): T {
  const outcome = schema.safeParse(value);
  if (outcome.success) return outcome.data;

  const all = validationFieldsFor(outcome.error.issues, part);

  throw ApiError.validationFailed(undefined, {
    details: {
      fields: all.slice(0, MAX_VALIDATION_FIELDS),
      truncated: all.length > MAX_VALIDATION_FIELDS,
    },
    cause: outcome.error,
  });
}
