-- ============================================================
-- 04-partitions.sql — monthly range partitions for the two event streams.
--
-- docs/02-HLD.md section 3.5 and the inline comment above session_events in
-- the authoritative schema both call for these two tables to be partitioned by
-- month and archived to the object store after ~90 days. The authoritative
-- schema creates them as ordinary tables, because a partitioned parent needs
-- the partition key in its primary key and the schema file is written to be
-- readable first. This file performs the conversion.
--
-- WHY A DROP AND RECREATE IS SAFE HERE, AND ONLY HERE
--
-- Container init scripts run exactly once, against a freshly initialised data
-- directory, before any application has connected. Both tables are guaranteed
-- empty at this point, and the guard below refuses to proceed if they are not.
-- The same conversion against a populated database is an entirely different
-- operation — create the partitioned table alongside, copy in batches, swap
-- under a lock — and that version belongs in a reviewed Drizzle migration in
-- packages/db, not in an init script.
--
-- TBD — owner: backend lead, decide by 2026-12-25 (M3 exit, when session_events
-- first carries real volume): move this conversion into packages/db as a
-- versioned migration and reduce this file to partition creation only.
-- ============================================================

\set ON_ERROR_STOP on

-- ------------------------------------------------------------
-- Guard
-- ------------------------------------------------------------
DO $guard$
DECLARE
    v_session_rows bigint;
    v_proctor_rows bigint;
BEGIN
    SELECT count(*) INTO v_session_rows FROM session_events;
    SELECT count(*) INTO v_proctor_rows FROM proctor_events;

    IF v_session_rows > 0 OR v_proctor_rows > 0 THEN
        RAISE EXCEPTION
            'Refusing to partition non-empty event tables (session_events=%, proctor_events=%)',
            v_session_rows, v_proctor_rows
        USING HINT = 'This script only runs against a fresh database. Converting a populated '
                     'table requires an online migration in packages/db.';
    END IF;
END
$guard$;


-- ============================================================
-- session_events
-- ============================================================
-- Recreated with:
--   * PARTITION BY RANGE (at) — `at` is the natural key, every query is
--     "this session, this time window", and retention is expressed in months.
--   * PRIMARY KEY (id, at) — Postgres requires the partition key to be part of
--     every unique constraint. The surrogate id stays for FK-free identity;
--     nothing references session_events, so widening its key costs nothing.
--   * identity rather than bigserial, which is the same thing with a sequence
--     the partitioned parent owns cleanly.
-- Column types, defaults and the FK are carried over unchanged from
-- docs/hiring_platform_schema.sql.
DROP TABLE IF EXISTS session_events;

CREATE TABLE session_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    session_id      uuid NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
    at              timestamptz NOT NULL DEFAULT now(),
    actor           text NOT NULL,          -- 'candidate' | 'interviewer'
    event_type      text NOT NULL,          -- edit | run | paste | language_change | ai_prompt
    payload         jsonb NOT NULL DEFAULT '{}',
    PRIMARY KEY (id, at)
) PARTITION BY RANGE (at);

-- Carried over from section 11 of the authoritative schema. Declared on the
-- parent, so every partition — including ones the rotation job creates years
-- from now — gets it automatically.
CREATE INDEX session_events_session_at_idx ON session_events (session_id, at);

COMMENT ON TABLE session_events IS
    'Interview replay stream. Partitioned monthly by `at`. Archived to object storage after 90 days.';


-- ============================================================
-- proctor_events
-- ============================================================
-- ADR-007 applies to every row in this table. These are advisory signals.
-- Nothing reads them to auto-reject, auto-void or down-score an attempt; they
-- are surfaced to a human reviewer with the evidence attached, and the human
-- decides. Partitioning is a storage and retention concern and changes none
-- of that.
DROP TABLE IF EXISTS proctor_events;

CREATE TABLE proctor_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    attempt_id      uuid NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
    at              timestamptz NOT NULL DEFAULT now(),
    event_type      text NOT NULL,          -- tab_blur | fullscreen_exit | paste | copy |
                                            -- devtools_open | multi_face | no_face | second_screen
    severity        smallint NOT NULL DEFAULT 1 CHECK (severity BETWEEN 1 AND 3),
    payload         jsonb NOT NULL DEFAULT '{}',
    PRIMARY KEY (id, at)
) PARTITION BY RANGE (at);

CREATE INDEX proctor_events_attempt_at_idx ON proctor_events (attempt_id, at);

COMMENT ON TABLE proctor_events IS
    'Advisory integrity signals (ADR-007). Never a decision input. Partitioned monthly by `at`.';


-- ------------------------------------------------------------
-- Re-apply row-level security
-- ------------------------------------------------------------
-- DROP TABLE took the policies created in 03-rls.sql with it. These are
-- identical to the declarations there; 03 remains the readable statement of
-- the isolation model, and this is the repair after the conversion.
ALTER TABLE session_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON session_events
    USING (EXISTS (SELECT 1 FROM interview_sessions s WHERE s.id = session_id))
    WITH CHECK (EXISTS (SELECT 1 FROM interview_sessions s WHERE s.id = session_id));

ALTER TABLE proctor_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY org_isolation ON proctor_events
    USING (EXISTS (SELECT 1 FROM attempts a WHERE a.id = attempt_id))
    WITH CHECK (EXISTS (SELECT 1 FROM attempts a WHERE a.id = attempt_id));


-- ============================================================
-- Partition creation
-- ============================================================
-- One function, used by this script and by the rotation job. Idempotent, so a
-- rotation run that overlaps a manual run is harmless.
--
-- Naming is `<parent>_yYYYYmMM`, which sorts correctly in \dt and makes the
-- DROP in the archival job unambiguous.
CREATE OR REPLACE FUNCTION public.ensure_event_partition(
    p_parent text,
    p_month  date
)
RETURNS text
LANGUAGE plpgsql
AS $fn$
DECLARE
    v_start date := date_trunc('month', p_month)::date;
    v_end   date := (date_trunc('month', p_month) + interval '1 month')::date;
    v_name  text := format('%s_y%sm%s', p_parent,
                           to_char(v_start, 'YYYY'), to_char(v_start, 'MM'));
BEGIN
    IF to_regclass(format('public.%I', v_name)) IS NOT NULL THEN
        RETURN v_name;
    END IF;

    EXECUTE format(
        'CREATE TABLE %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
        v_name, p_parent, v_start, v_end);

    -- Deny-all on the partition itself, and it has to be said here rather than
    -- inherited, because a partition does not inherit its parent's row-level
    -- security.
    --
    -- Postgres applies the *parent's* policies to rows reached through the
    -- parent, and a partition's own policies when the partition is named
    -- directly. A partition with RLS off is therefore a way round the parent's
    -- policy for anyone who can write its name -- and the names here are
    -- mechanical, `session_events_y2026m09`, so guessing one is not a feat.
    -- Enabling RLS with no policy denies every direct read and write; access
    -- through the parent is unaffected, because the parent's policy is what
    -- runs there.
    --
    -- Invariant 8 and migration 0002's completeness check, which is what found
    -- this: the check counts partitions, because Postgres counts them as
    -- tables in `public`, and it was right to.
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', v_name);

    RETURN v_name;
END
$fn$;

COMMENT ON FUNCTION public.ensure_event_partition(text, date) IS
    'Creates the monthly partition for a range-partitioned event table if it is absent. Idempotent.';

-- A DEFAULT partition catches anything outside the declared range. Without it
-- an insert with an unexpected timestamp fails outright, and an insert failing
-- means an interview event or an integrity signal is lost — which is worse
-- than a row landing in the wrong file. The rotation job alerts when the
-- default partition is non-empty, because a non-empty default means the job
-- has fallen behind.
CREATE TABLE session_events_default PARTITION OF session_events DEFAULT;
CREATE TABLE proctor_events_default PARTITION OF proctor_events DEFAULT;

-- Deny-all on the two defaults, for the reason given in ensure_event_partition
-- above: a partition does not inherit its parent's row-level security, and a
-- partition without it is a way round the parent's policy for anyone who can
-- name it. The default partition is the one whose name is easiest to guess.
ALTER TABLE session_events_default ENABLE ROW LEVEL SECURITY;
ALTER TABLE proctor_events_default ENABLE ROW LEVEL SECURITY;

-- Twelve months, starting the month the project starts (2026-09-21) and
-- running through 2027-08. Twelve is deliberate overshoot: the rotation job
-- keeps six months ahead, so a twelve-month runway means a rotation job that
-- has been broken for half a year still has not caused an outage. Finding out
-- from a monitoring alert beats finding out from a failed insert during an
-- exam window.
DO $seed$
DECLARE
    v_month date;
BEGIN
    FOR v_month IN
        SELECT generate_series(DATE '2026-09-01', DATE '2027-08-01', INTERVAL '1 month')::date
    LOOP
        PERFORM public.ensure_event_partition('session_events', v_month);
        PERFORM public.ensure_event_partition('proctor_events', v_month);
    END LOOP;
END
$seed$;


-- ============================================================
-- THE ROTATION JOB
--
-- Owner: apps/worker, as a BullMQ repeatable job. Planned, not built.
-- Milestone M3 (2026-11-30 → 2026-12-25) for session_events; M4
-- (2026-12-28 → 2027-01-22) adds the proctor_events retention half.
--
-- Schedule: daily at 03:15 UTC. Daily rather than monthly because a job that
-- runs twelve times a year is a job nobody notices is broken; a daily no-op
-- that suddenly starts doing work is a signal.
--
-- Each run, as the hiring_job role:
--
--   1. CREATE — call ensure_event_partition() for every month from the current
--      one through current + 6. Cheap, idempotent, and the reason a missing
--      partition never becomes an incident.
--
--   2. ALERT — count rows in session_events_default and proctor_events_default.
--      Non-zero means a partition was missing when a write arrived. Page on
--      it; the rows are safe but the invariant is broken.
--
--   3. ARCHIVE — for session_events partitions older than
--      RETENTION_SESSION_RECORDING_DAYS (default 90), copy the partition to
--      the object store as compressed newline-delimited JSON, verify the
--      object, then DETACH and DROP. Detach before drop so the parent stops
--      serving the data at a moment that is separate from the moment the data
--      stops existing — a failed verification is then recoverable.
--
--   4. ERASE — for proctor_events partitions older than
--      RETENTION_PROCTOR_MEDIA_DAYS (default 30), DROP without archiving.
--      Proctor signals are tied to biometric-adjacent media and the retention
--      policy for that media is deletion, not cold storage. Archiving them
--      would quietly defeat the policy. See docs/11-data-retention-and-dpia.md.
--
--   5. AUDIT — write one job.partition_rotate row to audit_log per run,
--      listing partitions created, archived and dropped. This is the
--      obligation hiring_job's BYPASSRLS carries (01-roles.sql).
--
-- The job never drops a partition that overlaps an attempt still in
-- `in_progress` or `under_review`. An integrity review with its evidence
-- deleted underneath it is worse than storage cost.
-- ============================================================

\echo 'Event partitions created through 2027-08. Rotation job: apps/worker, daily 03:15 UTC (M3).'
