/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * The question lifecycle, as a table.
 *
 * Four states crossed with four events is sixteen rows, and all sixteen are here — each
 * naming either the resulting state or the error code that rejected it. Written the way
 * `attempt-state.test.ts` is written, and for the same reason: a transition table tested
 * by example is a transition table with holes in it, and the holes are where a retired
 * question ends up back in front of a candidate.
 *
 * The rows are generated by crossing {@link QUESTION_LIFECYCLE_STATUSES} with
 * {@link QUESTION_EVENTS} rather than written out, so a fifth state or a fifth event
 * fails this file on the day it is added — with a missing-key type error at the table
 * literal, which is the failure that is impossible to misread.
 */

import { describe, expect, it } from 'vitest';

import { type DomainErrorCode } from './errors.js';
import {
  QUESTION_EVENTS,
  QUESTION_LIFECYCLE_STATUSES,
  canTransitionQuestion,
  isServableStatus,
  isTerminalQuestionStatus,
  transitionQuestion,
  type QuestionEvent,
  type QuestionStatus,
} from './question-lifecycle.js';

const EVENTS = {
  submit_for_review: { type: 'submit_for_review' },
  request_changes: { type: 'request_changes' },
  publish: { type: 'publish' },
  retire: { type: 'retire' },
} as const satisfies Record<QuestionEvent['type'], QuestionEvent>;

type EventKey = keyof typeof EVENTS;

const EVENT_KEYS = Object.keys(EVENTS) as EventKey[];

/** Either the state reached, or the `DomainErrorCode` that rejected the event. */
type Expectation = QuestionStatus | DomainErrorCode;

const ILLEGAL: DomainErrorCode = 'illegal_transition';

/**
 * The specification. Sixteen cells, no ellipsis, no "and so on".
 *
 * Read the `published` row first: it is the one with two legal events and it is where
 * ADR-003 lives. `publish` from `published` is the second-version case — publishing
 * version 4 of a live question leaves the question published — and `retire` is the only
 * way out. Everything else in that row is refused, including `request_changes`, because
 * the way to change a published question is a new version and not a status.
 */
const TABLE: Readonly<Record<QuestionStatus, Readonly<Record<EventKey, Expectation>>>> = {
  draft: {
    submit_for_review: 'review',
    request_changes: ILLEGAL,
    publish: ILLEGAL,
    retire: ILLEGAL,
  },
  review: {
    submit_for_review: ILLEGAL,
    request_changes: 'draft',
    publish: 'published',
    retire: ILLEGAL,
  },
  published: {
    submit_for_review: ILLEGAL,
    request_changes: ILLEGAL,
    publish: 'published',
    retire: 'retired',
  },
  retired: {
    submit_for_review: ILLEGAL,
    request_changes: ILLEGAL,
    publish: ILLEGAL,
    retire: ILLEGAL,
  },
};

const isStatus = (value: Expectation): value is QuestionStatus =>
  (QUESTION_LIFECYCLE_STATUSES as readonly string[]).includes(value);

describe('transitionQuestion', () => {
  const rows = QUESTION_LIFECYCLE_STATUSES.flatMap((from) =>
    EVENT_KEYS.map((eventKey) => ({ from, eventKey, expected: TABLE[from][eventKey] })),
  );

  it('covers every state crossed with every event', () => {
    expect(QUESTION_LIFECYCLE_STATUSES).toStrictEqual(['draft', 'review', 'published', 'retired']);
    expect(EVENT_KEYS).toStrictEqual(QUESTION_EVENTS);
    expect(rows).toHaveLength(QUESTION_LIFECYCLE_STATUSES.length * EVENT_KEYS.length);
    expect(rows).toHaveLength(16);
  });

  it.each(rows)('$from + $eventKey -> $expected', ({ from, eventKey, expected }) => {
    const result = transitionQuestion(from, EVENTS[eventKey]);

    if (isStatus(expected)) {
      expect(result).toStrictEqual({ ok: true, value: expected });
    } else {
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.error.code).toBe(expected);
        expect(result.error.message.length).toBeGreaterThan(0);
      }
    }
  });

  it('never produces a target that canTransitionQuestion rejects', () => {
    for (const { from, eventKey } of rows) {
      const result = transitionQuestion(from, EVENTS[eventKey]);
      if (result.ok) {
        expect(canTransitionQuestion(from, result.value)).toBe(true);
      }
    }
  });

  it('carries the offending state and event in the details, and nothing else', () => {
    const result = transitionQuestion('retired', { type: 'publish' });
    expect(result.ok).toBe(false);
    if (!result.ok) {
      // States and event names only. An error envelope is a place leaks hide (docs/14).
      expect(result.error.details).toStrictEqual({ from: 'retired', event: 'publish' });
    }
  });

  it('is a pure function of its arguments', () => {
    expect(transitionQuestion('review', { type: 'publish' })).toStrictEqual(
      transitionQuestion('review', { type: 'publish' }),
    );
  });
});

describe('the invariants the table encodes', () => {
  it('reaches published only from review or from published itself', () => {
    const predecessors = QUESTION_LIFECYCLE_STATUSES.filter((from) =>
      canTransitionQuestion(from, 'published'),
    );
    expect(predecessors).toStrictEqual(['review', 'published']);
  });

  it('never publishes a draft that nobody reviewed', () => {
    // The gate is the point of having a `review` state at all. A bank where an author can
    // publish their own unreviewed draft has a lifecycle with a review state in it and no
    // review in it.
    expect(canTransitionQuestion('draft', 'published')).toBe(false);
    expect(transitionQuestion('draft', { type: 'publish' }).ok).toBe(false);
  });

  it('makes retirement terminal: nothing leaves it, by any event', () => {
    expect(isTerminalQuestionStatus('retired')).toBe(true);
    for (const eventKey of EVENT_KEYS) {
      expect(transitionQuestion('retired', EVENTS[eventKey]).ok).toBe(false);
    }
    for (const to of QUESTION_LIFECYCLE_STATUSES) {
      expect(canTransitionQuestion('retired', to)).toBe(false);
    }
  });

  it('has exactly one terminal state', () => {
    expect(QUESTION_LIFECYCLE_STATUSES.filter(isTerminalQuestionStatus)).toStrictEqual(['retired']);
  });

  it('retires only what was in circulation', () => {
    // An unfinished draft is archived, not retired — a different axis (`archived_at`) and
    // a different word. Retirement means "this was being served and now is not".
    expect(canTransitionQuestion('draft', 'retired')).toBe(false);
    expect(canTransitionQuestion('review', 'retired')).toBe(false);
    expect(canTransitionQuestion('published', 'retired')).toBe(true);
  });

  it('offers no way back from published except retirement', () => {
    expect(canTransitionQuestion('published', 'draft')).toBe(false);
    expect(canTransitionQuestion('published', 'review')).toBe(false);
  });

  it('lets a live question publish a further version without leaving circulation', () => {
    // ADR-003's ordinary case once a bank is a few months old: the *version* went from
    // unpublished to published, and the *question* was already published and still is.
    expect(transitionQuestion('published', { type: 'publish' })).toStrictEqual({
      ok: true,
      value: 'published',
    });
  });

  it('lets a review bounce back to draft and round again', () => {
    const toReview = transitionQuestion('draft', { type: 'submit_for_review' });
    expect(toReview).toStrictEqual({ ok: true, value: 'review' });

    const bounced = transitionQuestion('review', { type: 'request_changes' });
    expect(bounced).toStrictEqual({ ok: true, value: 'draft' });

    // And the loop is not a trap: a bounced draft can be resubmitted.
    expect(transitionQuestion('draft', { type: 'submit_for_review' })).toStrictEqual({
      ok: true,
      value: 'review',
    });
  });
});

describe('isServableStatus', () => {
  it('admits published and nothing else', () => {
    expect(QUESTION_LIFECYCLE_STATUSES.filter(isServableStatus)).toStrictEqual(['published']);
  });

  it('refuses a retired question, which is the whole point of retiring one', () => {
    expect(isServableStatus('retired')).toBe(false);
  });
});
